/* const icerik = [
  {
    category: "Kahveler",
    category_id: 1,
    img: "../images/kahveler.svg",
  },
  {
    category: "Türk Kahvesi",
    category_id: 2,
    img: "../images/turkish.svg",
  },
  {
    category: "Sıcak İçecekler",
    category_id: 3,
    img: "../images/sicak.svg",
  },
  {
    category: "Soğuk Kahveler",
    category_id: 4,
    img: "../images/soguk_kahve.svg",
  },
  {
    category: "Soğuk İçecekler",
    category_id: 5,
    img: "../images/soguk_icecek.svg",
  },
  {
    category: "Sandwich",
    category_id: 6,
    img: "../images/tatli.svg",
  },
  {
    category: "Fil Special",
    category_id: 7,
    img: "../images/special.svg",
  },
];
 */
const menu = [
  /* kahveler */
  {
    id: 1,
    title: "Espresso",
    category: "Kahveler",
    category_id: 1,
    price: 21,
    img: "./images/espresso.jpg",
  },
  {
    id: 2,
    title: "Espresso Macchiato",
    category: "Kahveler",
    category_id: 1,
    price: 23,
    img: "./images/espresso-machiato.jpg",
  },
  {
    id: 3,
    title: "Latte",
    category: "Kahveler",
    category_id: 1,
    price: 26,
    img: "./images/latte.jpg",
  },
  {
    id: 4,
    title: "Espresso Cubano",
    category: "Kahveler",
    category_id: 1,
    price: 24,
    img: "./images/espresso-cubano.jpg",
  },
  {
    id: 5,
    title: "Espresso Romano",
    category: "Kahveler",
    category_id: 1,
    price: 24,
    img: "./images/espresso-romano.jpg",
  },
  {
    id: 6,
    title: "Americano",
    category: "Kahveler",
    category_id: 1,
    price: 24,
    img: "./images/americano.jpg",
  },
  {
    id: 7,
    title: "Cortado",
    category: "Kahveler",
    category_id: 1,
    price: 26,
    img: "./images/cortado.jpg",
  },
  {
    id: 8,
    title: "Mocha",
    category: "Kahveler",
    category_id: 1,
    price: 28,
    img: "./images/mocha.jpg",
  },
  {
    id: 9,
    title: "White Mocha",
    category: "Kahveler",
    category_id: 1,
    price: 28,
    img: "./images/white-mocha.jpg",
  },
  {
    id: 10,
    title: "Doppio",
    category: "Kahveler",
    category_id: 1,
    price: 23,
    img: "./images/doppio.jpg",
  },
  {
    id: 11,
    title: "Cappuccino",
    category: "Kahveler",
    category_id: 1,
    price: 26,
    img: "./images/cappucino.jpg",
  },
  {
    id: 12,
    title: "Flat White",
    category: "Kahveler",
    category_id: 1,
    price: 26,
    img: "./images/flat-white.jpg",
  },
  {
    id: 13,
    title: "Filtre Kahve",
    category: "Kahveler",
    category_id: 1,
    price: 25,
    img: "./images/filter-coffee.jpg",
  },
  {
    id: 14,
    title: "Red Eye",
    category: "Kahveler",
    category_id: 1,
    price: 26,
    img: "./images/red-eye.jpg",
  },
  {
    id: 15,
    title: "Black Eye",
    category: "Kahveler",
    category_id: 1,
    price: 28,
    img: "./images/red-eye.jpg",
  },
  {
    id: 16,
    title: "Death Eye",
    category: "Kahveler",
    category_id: 1,
    price: 30,
    img: "./images/death-eye.jpg",
  },
  /* Türk Kahvesi */
  {
    id: 17,
    title: "Klasik Türk Kahvesi",
    category: "Türk Kahvesi",
    category_id: 2,
    price: 20,
    img: "./images/turk-kahvesi.jpg",
  },
  {
    id: 18,
    title: "D. Sakızlı Türk Kahvesi",
    category: "Türk Kahvesi",
    category_id: 2,
    price: 23,
    img: "./images/damla-sakizli.jpg",
  },
  {
    id: 19,
    title: "Dibek Kahvesi",
    category: "Türk Kahvesi",
    category_id: 2,
    price: 23,
    img: "./images/dibek.jpg",
  },
  {
    id: 20,
    title: "Double Türk Kahvesi",
    category: "Türk Kahvesi",
    category_id: 2,
    price: 26,
    img: "./images/turk-kahvesi.jpg",
  },
  /* Sıcak İçecekler */
  {
    id: 21,
    title: "Çay",
    category: "Sıcak İçecekler",
    category_id: 3,
    price: 7,
    img: "./images/cay.jpg",
  },
  {
    id: 22,
    title: "Kupa Çay",
    category: "Sıcak İçecekler",
    category_id: 3,
    price: 12,
    img: "./images/kupa-cay.jpg",
  },
  {
    id: 23,
    title: "Sıcak Çikolata",
    category: "Sıcak İçecekler",
    category_id: 3,
    price: 23,
    img: "./images/hot-chocalate.jpg",
  },
  {
    id: 24,
    title: "Sahlep",
    category: "Sıcak İçecekler",
    category_id: 3,
    price: 23,
    img: "./images/sahlep.jpg",
  },
  {
    id: 25,
    title: "Beyaz Sıcak Çikolata",
    category: "Sıcak İçecekler",
    category_id: 3,
    price: 23,
    img: "./images/hot-chocalate-white.jpg",
  },
  {
    id: 26,
    title: "Bitki Çayı",
    category: "Sıcak İçecekler",
    category_id: 3,
    price: 23,
    img: "./images/herbal-tea.jpg",
    types: [
      "Papatya,",
      " Ihlamur,",
      " Kış Çayı,",
      " Orman Meyveleri,",
      " Ada Çayı,",
      " Yeşil Çay,",
    ],
  },
  /* Soğuk Kahveler */
  {
    id: 27,
    title: "Cold Brew",
    category: "Soğuk Kahveler",
    category_id: 4,
    price: 30,
    img: "./images/cold-brew.jpg",
  },
  {
    id: 28,
    title: "Soğuk Filtre Kahve",
    category: "Soğuk Kahveler",
    category_id: 4,
    price: 27,
    img: "./images/ice-filter.jpg",
  },
  {
    id: 29,
    title: "Buzlu Latte",
    category: "Soğuk Kahveler",
    category_id: 4,
    price: 28,
    img: "./images/ice-latte.jpg",
  },
  {
    id: 30,
    title: "Buzlu Mocha",
    category: "Soğuk Kahveler",
    category_id: 4,
    price: 30,
    img: "./images/ice-white-mocha.jpg",
  },
  {
    id: 31,
    title: "Buzlu White Mocha",
    category: "Soğuk Kahveler",
    category_id: 4,
    price: 30,
    img: "./images/ice-mocha.jpg",
  },
  {
    id: 32,
    title: "Affagato",
    category: "Soğuk Kahveler",
    category_id: 4,
    price: 26,
    img: "./images/affogato.jpg",
  },
  {
    id: 33,
    title: "Espresso Fredo",
    category: "Soğuk Kahveler",
    category_id: 4,
    price: 26,
    img: "./images/espresso-fredo.jpg",
  },
  {
    id: 34,
    title: "Buzlu Americano",
    category: "Soğuk Kahveler",
    category_id: 4,
    price: 26,
    img: "./images/ice-americano.jpg",
  },
  /* Soğuk İçeçekler */
  {
    id: 35,
    title: "Churcill",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 18,
    img: "./images/soda.jpg",
  },
  {
    id: 36,
    title: "Kutu İçecekler",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 13,
    img: "./images/ice-drink.jpg",
  },
  {
    id: 37,
    title: "İtalyan Soda",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 24,
    img: "./images/italian-soda.jpg",
  },
  {
    id: 38,
    title: "Milkshake",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 35,
    img: "./images/milkshake.jpg",
  },
  {
    id: 39,
    title: "Frozen",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 33,
    img: "./images/frozen.jpg",
  },
  {
    id: 40,
    title: "Frappe",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 35,
    img: "./images/frabbe.jpg",
  },
  {
    id: 41,
    title: "Limonata",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 20,
    img: "./images/lemonade.jpg",
  },
  {
    id: 42,
    title: "Soda",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 12,
    img: "./images/soda2.jpg",
  },
  {
    id: 43,
    title: "Meyveli Soda",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 14,
    img: "./images/meyveli-soda.jpg",
  },
  {
    id: 44,
    title: "Su",
    category: "Soğuk İçecekler",
    category_id: 5,
    price: 7,
    img: "./images/water.jpg",
  },
  /* Sandwich */
  {
    id: 45,
    title: "Fil Sandwich",
    category: "Sandwich",
    category_id: 6,
    price: 33,
    img: "./images/sandwich.jpg",
    types: ["Domates, Marul, Cheddar, Kaşar peyniri, Hindi Füme, Özel Fil Sos"],
  },
  /* Tatlılar */
  {
    id: 46,
    title: "San Sebastian",
    category: "Tatlılar",
    category_id: 7,
    price: 35,
    img: "./images/san-sebastian.jpg",
  },
  {
    id: 47,
    title: "Cookie",
    category: "Tatlılar",
    category_id: 7,
    price: 20,
    img: "./images/cookie.jpg",
  },
  {
    id: 48,
    title: "Muffin",
    category: "Tatlılar",
    category_id: 7,
    price: 20,
    img: "./images/muffin.jpg",
  },
  {
    id: 49,
    title: "Havuçlu Tarçınlı Kek",
    category: "Tatlılar",
    category_id: 7,
    price: 26,
    img: "./images/havuclu.jpg",
  },
  {
    id: 50,
    title: "Magnolya",
    category: "Tatlılar",
    category_id: 7,
    price: 29,
    img: "./images/magnolya.jpg",
  },
  /* Fil Special */
  {
    id: 51,
    title: "Soğuk Türk Kahvesi",
    category: "Fil Special",
    category_id: 7,
    price: 28,
    img: "./images/buzlu-turk.jpg",
  },
  {
    id: 52,
    title: "Fil Sıcak Çikolata",
    category: "Fil Special",
    category_id: 7,
    price: 30,
    img: "./images/blog-29.jpg",
  },
  {
    id: 53,
    title: "Hawaiin Latte",
    category: "Fil Special",
    category_id: 7,
    price: 30,
    img: "./images/hawain.jpg",
  },
  {
    id: 54,
    title: "PumpkinPie Latte",
    category: "Fil Special",
    category_id: 7,
    price: 30,
    img: "./images/pumpkin.jpg",
  },
];
export default menu;
